###############################################
# CONFIG
###############################################
import glob
import os

TSA_DB = "data/tsa_dbs/combined_db"
TSA_FASTA = "data/tsa_fasta_files/combined_target_species.fasta"
HMM_DB = "data/domains.hmm"

HCOL_FASTAS = sorted([os.path.basename(f) for f in glob.glob("data/hcol_fastas/*.fasta")])
HCOL_TYPES = [f.replace(".fasta", "") for f in HCOL_FASTAS]

###############################################
# RULE ALL
###############################################

rule all:
    input:
        expand("results/domain_mapping/{hcol}_analysis.csv", hcol=HCOL_TYPES),
        expand("results/final_summary/{hcol}_summary.csv", hcol=HCOL_TYPES)

###############################################
# BLAST TSA
###############################################

rule blast_tsa:
    input:
        fasta="data/hcol_fastas/{hcol}.fasta",
        db=multiext(TSA_DB,
            ".ndb",
            ".nhr",
            ".nin",
            ".not",
            ".nsq",
            ".ntf",
            ".nto")
    output:
        final="results/blast/{hcol}_final.tsv",
        temp_raw=temp("results/blast/{hcol}_raw.tsv"),
        temp_parsed=temp("results/blast/{hcol}_parsed.tsv")
    threads: 8
    params:
        db_prefix=TSA_DB
    shell:
        """
        module load tools/env/proxy
        module load apps/binapps/blast/2.17.0

        tblastn \
            -query {input.fasta} \
            -db {params.db_prefix} \
            -outfmt "6 qseqid sseqid pident length qcovs evalue bitscore stitle" \
            -evalue 1e-3 \
            -seg no \
            -soft_masking false \
            -num_threads {threads} \
            > {output.temp_raw}

        awk -F'\t' 'BEGIN{{OFS="\t"}} {{
            match($8, /TSA: ([A-Za-z]+ [A-Za-z0-9\.\-]+)/, arr);
            species = (arr[1] ? arr[1] : "Unknown");
            gsub(/sp\./, "sp", species);
            print $1, $2, $3, $4, $5, $6, $7, species
            }}' {output.temp_raw} > {output.temp_parsed}

        LC_ALL=C sort -t$'\t' -k8,8 -k7,7nr -k6,6g {output.temp_parsed} \
        | awk -F'\t' '!seen[$8]++' \
        > {output.final}

        sed -i '1i qseqid\tsseqid\tpident\tlength\tqcovs\tevalue\tbitscore\tspecies' {output.final}
        """

###############################################
# EXTRACT FASTAS
###############################################

rule extract_fasta:
    input:
        blast="results/blast/{hcol}_final.tsv",
        tsa_fasta=TSA_FASTA
    output:
        "results/extracted_fastas/{hcol}_extracted.fasta"
    script:
        "scripts/pull_fasta.py"

###############################################
# LONGEST ORF
###############################################

rule longest_orf:
    input:
        "results/extracted_fastas/{hcol}_extracted.fasta"
    output:
        final_orf="results/orfs/{hcol}_longest_orfs.fasta"
    conda:
        "envs/orfipy.yaml"
    run:
        if os.path.getsize(input[0]) == 0:
            shell("touch {output.final_orf}")
        else:
            shell("""
                export OMP_NUM_THREADS=1
                export OPENBLAS_NUM_THREADS=1
                export MKL_NUM_THREADS=1
                export NUMEXPR_NUM_THREADS=1

                TMP_DIR="results/orfs/{wildcards.hcol}_tmp"
                mkdir -p "$TMP_DIR"

                orfipy {input} \
                    --pep {wildcards.hcol}_all_orfs.pep \
                    --outdir "$TMP_DIR" \
                    --procs 2

                seqkit sort -l -r "$TMP_DIR"/{wildcards.hcol}_all_orfs.pep \
                    -o "$TMP_DIR"/{wildcards.hcol}_sorted.pep

                seqkit rmdup -i --id-regexp "^([^._]+)" \
                    "$TMP_DIR"/{wildcards.hcol}_sorted.pep \
                    > {output.final_orf}

                rm -rf "$TMP_DIR"
            """)

###############################################
# DOMAIN ARCHITECTURE & CLASSIFICATION
###############################################

rule domain_architecture:
    input:
        pep="results/orfs/{hcol}_longest_orfs.fasta",
        hmm_db=HMM_DB
    output:
        csv="results/domain_mapping/{hcol}_analysis.csv",
        plot_dir=directory("results/domain_mapping/plots/{hcol}")
    script:
        "scripts/domain_architecture.py"

###############################################
# COMPILE FINAL RESULTS
###############################################

rule compile_final_results:
    input:
        blast="results/blast/{hcol}_final.tsv",
        orfs="results/orfs/{hcol}_longest_orfs.fasta",
        fasta="results/extracted_fastas/{hcol}_extracted.fasta",
        domains="results/domain_mapping/{hcol}_analysis.csv"
    output:
        summary="results/final_summary/{hcol}_summary.csv"
    params:
        hcol_type="{hcol}"
    script:
        "scripts/compile_summary.py"